name: BowlerTrax
options:
  bundleIdPrefix: com.bowlertrax
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_PREVIEWS: YES

configs:
  Debug:
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    SWIFT_COMPILATION_MODE: singlefile
  Release:
    SWIFT_OPTIMIZATION_LEVEL: "-O"
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    SWIFT_COMPILATION_MODE: wholemodule

targets:
  BowlerTrax:
    type: application
    platform: iOS
    sources:
      - path: BowlerTrax
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bowlertrax.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_CFBundleDisplayName: BowlerTrax
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_NSCameraUsageDescription: "BowlerTrax needs camera access to track your bowling shots and provide real-time analytics."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "BowlerTrax needs photo library access to save and export your session videos."
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      configs:
        Debug:
          OTHER_SWIFT_FLAGS: "-D DEBUG"
        Release:
          OTHER_SWIFT_FLAGS: ""
    entitlements:
      path: BowlerTrax/BowlerTrax.entitlements
      properties:
        com.apple.developer.healthkit: false

schemes:
  BowlerTrax:
    build:
      targets:
        BowlerTrax: all
    run:
      config: Debug
      environmentVariables:
        - variable: IDEPreferLogStreaming
          value: "YES"
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
